import { describe, expect, it } from "vitest";

import type { PatchResult } from "./patch";
import { patchNextLayout, patchViteConfig } from "./patch";

const CREATE_NEXT_APP_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={\`\${geistSans.variable} antialiased\`}
      >
        {children}
      </body>
    </html>
  );
}
`;

const patched = (result: PatchResult) => {
  if (result.status !== "patched") {
    throw new Error(`expected a patch, got ${JSON.stringify(result)}`);
  }
  return result.code;
};

describe(patchNextLayout, () => {
  it("patches the create-next-app layout and is idempotent", () => {
    const code = patched(patchNextLayout(CREATE_NEXT_APP_LAYOUT));
    expect(code).toBe(
      CREATE_NEXT_APP_LAYOUT.replace(
        'import "./globals.css";\n',
        'import "./globals.css";\nimport { ShadcnLabsDevtools } from "@shadcn-labs/devtools-next";\n'
      ).replace(
        "        {children}\n      </body>",
        "        {children}\n        <ShadcnLabsDevtools />\n      </body>"
      )
    );
    expect(patchNextLayout(code)).toStrictEqual({ status: "already" });
  });

  it("follows multi-line imports, tabs and CRLF", () => {
    const source = [
      "import {",
      "\tInter,",
      "} from 'next/font/google' // font",
      "import { cn } from '@/lib/utils'",
      "",
      "export default function Layout({ children }) {",
      "\treturn (",
      "\t\t<html>",
      "\t\t\t<body",
      "\t\t\t\tclassName={cn(",
      "\t\t\t\t\t'min-h-screen',",
      "\t\t\t\t\tinter.className",
      "\t\t\t\t)}",
      "\t\t\t>",
      "\t\t\t\t<Providers>{children}</Providers>",
      "\t\t\t</body>",
      "\t\t</html>",
      "\t)",
      "}",
      "",
    ].join("\r\n");
    expect(patched(patchNextLayout(source)).split("\r\n")).toStrictEqual([
      "import {",
      "\tInter,",
      "} from 'next/font/google' // font",
      "import { cn } from '@/lib/utils'",
      "import { ShadcnLabsDevtools } from '@shadcn-labs/devtools-next'",
      "",
      "export default function Layout({ children }) {",
      "\treturn (",
      "\t\t<html>",
      "\t\t\t<body",
      "\t\t\t\tclassName={cn(",
      "\t\t\t\t\t'min-h-screen',",
      "\t\t\t\t\tinter.className",
      "\t\t\t\t)}",
      "\t\t\t>",
      "\t\t\t\t<Providers>{children}</Providers>",
      "\t\t\t\t<ShadcnLabsDevtools />",
      "\t\t\t</body>",
      "\t\t</html>",
      "\t)",
      "}",
      "",
    ]);
  });

  it("inserts inline when </body> shares a line and reuses an existing import", () => {
    const source = `import { ShadcnLabsDevtools } from "@shadcn-labs/devtools-next";

export default function Layout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    expect(patched(patchNextLayout(source))).toBe(
      source.replace(
        "{children}</body>",
        "{children}<ShadcnLabsDevtools /></body>"
      )
    );
  });

  it("indents one level inside an empty body", () => {
    const source = `export default function Layout() {
    return (
        <body>
        </body>
    );
}
`;
    expect(patched(patchNextLayout(source))).toBe(
      `import { ShadcnLabsDevtools } from "@shadcn-labs/devtools-next";

export default function Layout() {
    return (
        <body>
            <ShadcnLabsDevtools />
        </body>
    );
}
`
    );
  });

  it("refuses layouts it cannot patch safely", () => {
    expect(patchNextLayout("export default () => <main />;\n").status).toBe(
      "unsupported"
    );
    expect(
      patchNextLayout(
        '"use client";\nexport default ({ c }) => <body>{c}</body>;\n'
      ).status
    ).toBe("unsupported");
    expect(
      patchNextLayout("const a = <body></body>;\nconst b = <body></body>;\n")
        .status
    ).toBe("unsupported");
  });
});

describe(patchViteConfig, () => {
  it("prepends to an inline plugins array in create-vite style", () => {
    const source = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
})
`;
    const result = patchViteConfig(source);
    expect(result).toStrictEqual({
      code: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { shadcnLabsDevtools } from '@shadcn-labs/devtools-vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [shadcnLabsDevtools(), react()],
})
`,
      status: "patched",
    });
    expect(
      patchViteConfig(result.status === "patched" ? result.code : "")
    ).toStrictEqual({ status: "already" });
  });

  it("prepends to a multi-line array inside a config function", () => {
    const source = `import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    tailwindcss(),
  ],
  server: { port: mode === "test" ? 0 : 5173 },
}));
`;
    expect(patchViteConfig(source)).toStrictEqual({
      code: source
        .replace(
          'import { defineConfig } from "vite";\n',
          'import { defineConfig } from "vite";\nimport { shadcnLabsDevtools } from "@shadcn-labs/devtools-vite";\n'
        )
        .replace("  plugins: [\n", "  plugins: [\n    shadcnLabsDevtools(),\n"),
      status: "patched",
    });
  });

  it("fills empty arrays", () => {
    const inline = patchViteConfig(
      'import { defineConfig } from "vite";\nexport default defineConfig({ plugins: [] });\n'
    );
    expect(inline.status === "patched" && inline.code).toContain(
      "plugins: [shadcnLabsDevtools()]"
    );
    const multiline = patchViteConfig(
      'import { defineConfig } from "vite";\nexport default defineConfig({\n  plugins: [\n  ],\n});\n'
    );
    expect(multiline.status === "patched" && multiline.code).toContain(
      "  plugins: [\n    shadcnLabsDevtools(),\n  ],"
    );
  });

  it("refuses configs without exactly one plugins array", () => {
    expect(
      patchViteConfig(
        'import { defineConfig } from "vite";\nexport default defineConfig({ server: { port: 3000 } });\n'
      )
    ).toStrictEqual({
      reason: "no `plugins: [...]` array found",
      status: "unsupported",
    });
    expect(
      patchViteConfig(
        "export default { plugins: [a()], build: { rollupOptions: { plugins: [b()] } } };\n"
      ).status
    ).toBe("unsupported");
    expect(
      patchViteConfig(
        "const react = require('@vitejs/plugin-react');\nmodule.exports = { plugins: [react()] };\n"
      ).status
    ).toBe("unsupported");
  });
});
